<?php

namespace AppBundle\Repository;

/**
 * UserAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAppRepository extends \Doctrine\ORM\EntityRepository
{
}
